/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef timing_pal_3_H
#define timing_pal_3_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "timing_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* PAL instance information */
extern const timing_instance_t timingFtmInst0;

/* Channel configuration array */
extern const timer_chan_config_t timingFtmInst0_chanConfig[1];

/* FTM specific extension configuration */
extern extension_ftm_for_timer_t timingFtmInst0_extension;

/* Timing configuration */
extern const timer_config_t timingFtm_InitConfig0;

/* Callback function of channel configuration 0 */
extern void timingFtmInst0_callback(void * userData);



#endif /* timing_pal_3_H */
