/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef scst_H
#define scst_H

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "m4_scst_test_shell.h"



#endif /* scst_H */
