/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 7ba705e1-e83b-4ac6-af47-d25b0055e4b4
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_AMMCLib1.h"

/*******************************************************************************
 * AMMCLib1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'AMMCLib1'
- type: 'ammclib'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'ammclib'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - ammclib_cfg_set:
    - ammclib_fixedPoint: 'true'
    - ammclib_float: 'true'
    - ammclib_defaultImpl: 'SWLIBS_DEFAULT_IMPLEMENTATION_FLT'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/*
 * This file is generated automatically by AMMCLib component
 * and is intentionally left empty
 */

