/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_erm_config_1.h"

/*******************************************************************************
 * erm_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'erm_config_1'
- type: 'erm_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'erm'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ERM'
- config_sets:
  - erm:
    - ermConfigArray:
      - 0:
        - name: 'erm_InitConfig0'
        - userConfigReadOnly: 'true'
        - ermChannelConfigArray:
          - 0:
            - channel: '0'
            - interruptCfg: 'erm_Interrupt0'
          - 1:
            - channel: '1'
            - interruptCfg: 'erm_Interrupt0'
    - ermInterruptConfigArray:
      - 0:
        - name: 'erm_Interrupt0'
        - interruptConfigReadOnly: 'true'
        - singleBitInterruptEnable: 'true'
        - nonCorrectableInterruptEnable: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */


/* Interrupt configurations */

/* Interrupt configuration 0 */
const erm_interrupt_config_t erm_Interrupt0 =
{
    .enableSingleCorrection = true,
    .enableNonCorrectable = true
};

/* ERM configurations */

/* ERM configuration 0 */
const erm_user_config_t erm_InitConfig0[ERM_CHANNEL_COUNT0] =
{
    /* Channel configuration 0 */
    {
        .channel = 0U,
        .interruptCfg = &erm_Interrupt0
    },
    /* Channel configuration 1 */
    {
        .channel = 1U,
        .interruptCfg = &erm_Interrupt0
    }
};

