/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef erm_config_1_H
#define erm_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "erm_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/* ERM instance number configured */
#define INST_ERM_CONFIG_1  (0U)

/* Number of configured channels for ERM instances */
#define ERM_CHANNEL_COUNT0  (2U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User configurations */

/* Interrupt configurations */
extern const erm_interrupt_config_t erm_Interrupt0;

/* ERM configurations */
extern const erm_user_config_t erm_InitConfig0[ERM_CHANNEL_COUNT0];



#endif /* erm_config_1_H */
