/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef MPU_PAL_CFG_H
#define MPU_PAL_CFG_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define MPU_OVER_MPU  1

#define MPU_OVER_MPU_INSTANCE_COUNT  1

#endif /* MPU_PAL_CFG_H */

