/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: c6f0dc65-4367-4230-a391-f3e2380ae1c1
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_pwrMan1.h"

/*******************************************************************************
 * pwrMan1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'pwrMan1'
- type: 'power_manager'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'power_manager'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'POWER_MANAGER'
- config_sets:
  - power_manager:
    - POWER_CONFIGURATIONS:
      - powerModeConfiguration:
        - 0:
          - powerModeConfig: 'pwrMan1_InitConfig0'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_STOP1'
        - 1:
          - powerModeConfig: 'power_manager_InitConfig1'
          - sleepOnExitValue: 'false'
          - powerMode: 'POWER_MANAGER_RUN'
      - Callback: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/*! @brief User Configuration structure pwrMan1_InitConfig0 */
power_manager_user_config_t pwrMan1_InitConfig0 = {
    .powerMode                = POWER_MANAGER_STOP1,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief User Configuration structure power_manager_InitConfig1 */
power_manager_user_config_t power_manager_InitConfig1 = {
    .powerMode                = POWER_MANAGER_RUN,     /*!< Power manager mode */
    .sleepOnExitValue         = false,          /*!< Sleep on exit value */
};

/*! @brief Array of pointers to User configuration structures */
power_manager_user_config_t * powerConfigsArr[] = {
    &pwrMan1_InitConfig0,
    &power_manager_InitConfig1
};

/*! @brief Array of pointers to User defined Callbacks configuration structures */
power_manager_callback_user_config_t * powerStaticCallbacksConfigsArr[] = {(void *)0};


