/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef timing_pal_2_H
#define timing_pal_2_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "timing_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* PAL instance information */
extern const timing_instance_t timingLptmrInst0;

/* Channel configuration array */
extern const timer_chan_config_t timingLptmrInst0_chanConfig[1];

/* LPTMR specific extension configuration */
extern extension_lptmr_for_timer_t timingLptmrInst0_extension;

/* Timing configuration */
extern const timer_config_t timingLptmr_InitConfig0;

/* Callback function of channel configuration 0 */
extern void timingLptmrInst0_callback(void * userData);



#endif /* timing_pal_2_H */
