/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef ewm_config_1_H
#define ewm_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * There are global macros defined to be used by the integrator and another one used as include guard.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "ewm_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/* EWM instance number configured */
#define EWM_CONFIG_1  (0U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User configuration structures */

/* User configuration 0 */
extern const ewm_init_config_t ewm_Config0;



#endif /* ewm_config_1_H */
