/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 8f74fc8a-8989-4964-a5f1-43bb6786778f
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_lpi2c1.h"

/*******************************************************************************
 * lpi2c1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lpi2c1'
- type: 'lpi2c_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'lpi2c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C0'
- config_sets:
  - lpi2c:
    - masterConfigurationLPI2C:
      - 0:
        - name: 'lpi2c1_MasterConfig0'
        - readonly: 'true'
        - lpi2c_master_cfg_slaveAddress: '0'
        - lpi2c_master_cfg_is10bitAddr: 'false'
        - lpi2c_master_cfg_operatingMode: 'LPI2C_STANDARD_MODE'
        - lpi2c_master_cfg_baudRate: '0'
        - lpi2c_master_cfg_transferType: 'LPI2C_USING_INTERRUPTS'
        - lpi2c_master_cfg_dmaChannel: '0'
        - lpi2c_master_cfg_masterCallback: 'lpi2c1_MasterCallback0'
        - lpi2c_master_cfg_callbackParam: 'NULL'
    - slaveConfigurationLPI2C:
      - 0:
        - name: 'lpi2c1_SlaveConfig0'
        - readonly: 'false'
        - lpi2c_slave_cfg_slaveAddress: '37'
        - lpi2c_slave_cfg_is10bitAddr: 'false'
        - lpi2c_slave_cfg_operatingMode: 'LPI2C_FAST_MODE'
        - lpi2c_slave_cfg_slaveListening: 'true'
        - lpi2c_slave_cfg_transferType: 'LPI2C_USING_INTERRUPTS'
        - lpi2c_slave_cfg_dmaChannel: '0'
        - lpi2c_slave_cfg_slaveCallback: 'lpi2c1_SlaveCallback0'
        - lpi2c_slave_cfg_callbackParam: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

const lpi2c_master_user_config_t lpi2c1_MasterConfig0 = {
  .slaveAddress = 0U,
  .is10bitAddr = false,
  .operatingMode = LPI2C_STANDARD_MODE,
  .baudRate = 0UL,
  .transferType = LPI2C_USING_INTERRUPTS,
  .dmaChannel = 0U,
  .masterCallback = lpi2c1_MasterCallback0,
  .callbackParam = NULL
};

lpi2c_slave_user_config_t lpi2c1_SlaveConfig0 = {
  .slaveAddress = 37U,
  .is10bitAddr = false,
  .operatingMode = LPI2C_FAST_MODE,
  .slaveListening = true,
  .transferType = LPI2C_USING_INTERRUPTS,
  .dmaChannel = 0U,
  .slaveCallback = lpi2c1_SlaveCallback0,
  .callbackParam = NULL
};


