/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: ceb2e5d3-05f7-4f92-a4fd-1f63e4146c80
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_lpit1.h"

/*******************************************************************************
 * lpit1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lpit1'
- type: 'lpit_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'lpit'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPIT_0'
- config_sets:
  - lpit:
    - lpitConfig:
      - name: 'lpit1_InitConfig'
      - enableRunInDebug: 'false'
      - enableRunInDoze: 'false'
    - lpitChannelConfig:
      - 0:
        - name: 'lpit1_ChnConfig0'
        - cfgReadOnly: 'true'
        - timerMode: 'LPIT_PERIODIC_COUNTER'
        - periodUnits: 'LPIT_PERIOD_UNITS_MICROSECONDS'
        - period: '100000'
        - triggerSource: 'LPIT_TRIGGER_SOURCE_INTERNAL'
        - triggerSelect: '0U'
        - enableReloadOnTrigger: 'false'
        - enableStopOnInterrupt: 'false'
        - enableStartOnTrigger: 'false'
        - chainChannel: 'false'
        - isInterruptEnabled: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* lPIT global configuration */
const lpit_user_config_t  lpit1_InitConfig = {
  .enableRunInDebug = false,
  .enableRunInDoze = false
};

/* Channel configuration 0*/
const lpit_user_channel_config_t  lpit1_ChnConfig0 = {
  .timerMode = LPIT_PERIODIC_COUNTER,
  .periodUnits = LPIT_PERIOD_UNITS_MICROSECONDS,
  .period = 100000UL,
  .triggerSource = LPIT_TRIGGER_SOURCE_INTERNAL,
  .triggerSelect = 0U,
  .enableReloadOnTrigger = false,
  .enableStopOnInterrupt = false,
  .enableStartOnTrigger = false,
  .chainChannel = false,
  .isInterruptEnabled = true
};


