/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: ceb2e5d3-05f7-4f92-a4fd-1f63e4146c80
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_sbc_uja116x.h"

/*******************************************************************************
 * sbc_uja116x initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'sbc_uja116x'
- type: 'sbc_uja116x_driver'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'sbc_uja116x'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - sbc_uja116x_driver:
    - sbcDevModel: '0_LV'
    - sbcSpi:
      - spi_t: 'lpspiCom1'
      - spiConfig: '0'
    - sbcCfgArray:
      - 0:
        - name: 'sbc_uja116x_InitConfig0'
        - ro: 'true'
        - regulatorCtr:
          - regulator:
            - pdc: 'SBC_UJA_REGULATOR_PDC_HV'
            - v2c: 'SBC_UJA_REGULATOR_V2C_OFF'
            - v1rtc: 'SBC_UJA_REGULATOR_V1RTC_90'
          - supplyEvnt:
            - v2oe: 'SBC_UJA_SUPPLY_EVNT_V2OE_DIS'
            - v2ue: 'SBC_UJA_SUPPLY_EVNT_V2UE_DIS'
            - v1ue: 'SBC_UJA_SUPPLY_EVNT_V1UE_DIS'
        - watchdog:
          - modeControl: 'SBC_UJA_WTDOG_CTR_WMC_AUTO'
          - nominalPeriod: 'SBC_UJA_WTDOG_CTR_NWP_128'
        - mode: 'SBC_UJA_MODE_MC_NORMAL'
        - lhc: 'SBC_UJA_FAIL_SAFE_LHC_FLOAT'
        - sysEvnt:
          - owte: 'SBC_UJA_SYS_EVNT_OTWE_DIS'
          - spife: 'SBC_UJA_SYS_EVNT_SPIFE_DIS'
        - lockMask:
          - LK0C: 'false'
          - LK1C: 'false'
          - LK2C: 'false'
          - LK3C: 'false'
          - LK4C: 'false'
          - LK5C: 'false'
          - LK6C: 'false'
        - can:
          - canConf:
            - cmc: 'SBC_UJA_CAN_CMC_OFMODE'
          - canTransEvnt:
            - cbse: 'SBC_UJA_TRANS_EVNT_CBSE_DIS'
            - cfe: 'SBC_UJA_TRANS_EVNT_CFE_DIS'
            - cwe: 'SBC_UJA_TRANS_EVNT_CWE_EN'
        - wakePin:
          - wpre: 'SBC_UJA_WAKE_EN_WPRE_EN'
          - wpfe: 'SBC_UJA_WAKE_EN_WPFE_EN'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* SBC UJA116xA Configuration 0 - device: UJA1169ATK. */
const sbc_int_config_t sbc_uja116x_InitConfig0 =
{
    /* Regulator control register group. */
    .regulatorCtr =
    {
        /* Regulator control register. */
        .regulator =
        {
            .pdc   = SBC_UJA_REGULATOR_PDC_HV,
            .v2c   = SBC_UJA_REGULATOR_V2C_OFF,
            .v1rtc = SBC_UJA_REGULATOR_V1RTC_90,
        },
        /* Supply event capture enable register. */
        .supplyEvnt =
        {
            .v2oe = SBC_UJA_SUPPLY_EVNT_V2OE_DIS,
            .v2ue = SBC_UJA_SUPPLY_EVNT_V2UE_DIS,
            .v1ue = SBC_UJA_SUPPLY_EVNT_V1UE_DIS,
        },
    },
    /* Watchdog control register. */
    .watchdog =
    {
        .modeControl   = SBC_UJA_WTDOG_CTR_WMC_AUTO,
        .nominalPeriod = SBC_UJA_WTDOG_CTR_NWP_128,
    },
    /* Mode control register. */
    .mode = SBC_UJA_MODE_MC_NORMAL,
    /* LIMP home control. */
    .lhc = SBC_UJA_FAIL_SAFE_LHC_FLOAT,
    /* System event capture enable registers. */
    .sysEvnt =
    {
        .owte  = SBC_UJA_SYS_EVNT_OTWE_DIS,
        .spife = SBC_UJA_SYS_EVNT_SPIFE_DIS,
    },
    /* Lock control register. */
    .lockMask = (sbc_lock_t)( SBC_UJA_LOCK_LK0C_F(0U) \
            | SBC_UJA_LOCK_LK1C_F(0U) \
            | SBC_UJA_LOCK_LK2C_F(0U) \
            | SBC_UJA_LOCK_LK3C_F(0U) \
            | SBC_UJA_LOCK_LK4C_F(0U) \
            | SBC_UJA_LOCK_LK5C_F(0U) \
            | SBC_UJA_LOCK_LK6C_F(0U) ),
    /* CAN configuration group. */
    .can =
    {
        /* CAN control register. */
        .canConf =
        {
            .cfdc  = SBC_UJA_CAN_CFDC_DIS,  /* Not available on UJA1169TK. */
            .pncok = SBC_UJA_CAN_PNCOK_DIS, /* Not available on UJA1169TK. */
            .cpnc  = SBC_UJA_CAN_CPNC_DIS,  /* Not available on UJA1169TK. */
            .cmc   = SBC_UJA_CAN_CMC_OFMODE,
        },
        /* Transceiver event capture enable register. */
        .canTransEvnt =
        {
            .cbse = SBC_UJA_TRANS_EVNT_CBSE_DIS,
            .cfe  = SBC_UJA_TRANS_EVNT_CFE_DIS,
            .cwe  = SBC_UJA_TRANS_EVNT_CWE_EN,
        },
        /* CAN data rate selection. */
        .datRate = SBC_UJA_DAT_RATE_CDR_50KB, /* Not available on UJA1169TK. */
        /* ID registers. */
        .identif =
        {
            (sbc_identifier_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identifier_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identifier_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identifier_t) 0U, /* Not available on UJA1169TK. */
        },
        /* ID mask registers. */
        .mask =
        {
            (sbc_identif_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identif_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identif_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_identif_mask_t) 0U, /* Not available on UJA1169TK. */
        },
        /* Frame control register. */
        .frame =
        {
            .ide  = SBC_UJA_FRAME_CTR_IDE_11B,    /* Not available on UJA1169TK. */
            .pndm = SBC_UJA_FRAME_CTR_PNDM_DCARE, /* Not available on UJA1169TK. */
            .dlc  = (sbc_frame_ctr_dlc_t) 0U,     /* Not available on UJA1169TK. */
        },
        /* Data mask 0 - 7 configuration. */
        .dataMask =
        {
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
            (sbc_data_mask_t) 0U, /* Not available on UJA1169TK. */
        },
    },
    /* WAKE pin event capture enable register. */
    .wakePin =
    {
        .wpre = SBC_UJA_WAKE_EN_WPRE_EN,
        .wpfe = SBC_UJA_WAKE_EN_WPFE_EN,
    },
};



