/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_pwm_pal_1.h"

/*******************************************************************************
 * pwm_pal_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'pwm_pal_1'
- type: 'pwm_pal_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pwm_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM_0'
- config_sets:
  - pwm_pal:
    - pwmGlobalDeadtimeConfig:
      - deadtime: '0'
    - pwmGlobalConfigArray:
      - 0:
        - name: 'config_pwm_pal_0'
        - channel: '1'
        - channelType: 'PWM_EDGE_ALIGNED'
        - period: '5000'
        - duty: '2500'
        - polarity: 'PWM_ACTIVE_HIGH'
        - insertDeadtime: 'false'
        - enableComplementaryChannel: 'false'
        - complementaryChannelPolarity: 'PWM_DUPLICATED'
        - timebase: 'Timebase 0'
    - pwmTimebaseConfigArray:
      - 0:
        - sourceClock: 'FTM_CLOCK_SOURCE_SYSTEMCLK'
        - prescaler: 'FTM_CLOCK_DIVID_BY_1'
        - deadtimePrescaler: 'FTM_DEADTIME_DIVID_BY_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/*! @brief PWM_PAL Timebase configuration*/
pwm_ftm_timebase_t pwm_pal_1_timebase0 = 
{
    .sourceClock = FTM_CLOCK_SOURCE_SYSTEMCLK,
    .prescaler = FTM_CLOCK_DIVID_BY_1,
    .deadtimePrescaler = FTM_DEADTIME_DIVID_BY_1
};

/*! @brief PWM_PAL Channel configuration */
pwm_channel_t pwm_pal_1_channels[1] = 
{
    {
        .channel = 1,
        .channelType = PWM_EDGE_ALIGNED,
        .period = 5000,
        .duty = 2500,
        .polarity = PWM_ACTIVE_HIGH,
        .insertDeadtime = false,
        .deadtime = 0,
        .enableComplementaryChannel = false,
        .complementaryChannelPolarity = PWM_DUPLICATED,
        .timebase = &pwm_pal_1_timebase0,
    },
};

/*! @brief PWM_PAL Initialization configuration */
pwm_global_config_t pwm_pal_1_configs = 
{
    .pwmChannels = pwm_pal_1_channels,
    .numberOfPwmChannels = 1,
};
/*! @brief PWM_PAL instance information */
pwm_instance_t pwm_pal_1_instance = 
{
    .instType = PWM_INST_TYPE_FTM,
    .instIdx = 0,
};


