function init() {
    return[
        {"area_en":"Canada","area":"加拿大","area_code":1,"country":"northAmerica","country_code":5},
        {"area_en":"United States of America","area":"美国","area_code":1,"country":"northAmerica","country_code":5},
        {"area_en":"Kazakhstan","area":"哈萨克斯坦","area_code":7,"country":"centralAsia","country_code":1},
        {"area_en":"Russia","area":"俄罗斯","area_code":7,"country":"eastEurope","country_code":2},
        {"area_en":"Egypt","area":"埃及","area_code":20,"country":"northAfrica","country_code":3},
        {"area_en":"South Africa","area":"南非","area_code":27,"country":"southAfrica","country_code":3},
        {"area_en":"Greece","area":"希腊","area_code":30,"country":"southEurope","country_code":2},
        {"area_en":"Netherlands","area":"荷兰","area_code":31,"country":"westEurope","country_code":2},
        {"area_en":"Belgium","area":"比利时","area_code":32,"country":"westEurope","country_code":2},
        {"area_en":"France","area":"法国","area_code":33,"country":"westEurope","country_code":2},
        {"area_en":"Spain","area":"西班牙","area_code":34,"country":"southEurope","country_code":2},
        {"area_en":"Hungary","area":"匈牙利","area_code":36,"country":"centralEurope","country_code":2},
        {"area_en":"Italy","area":"意大利","area_code":39,"country":"southEurope","country_code":2},
        {"area_en":"Romania","area":"罗马尼亚","area_code":40,"country":"southEurope","country_code":2},
        {"area_en":"Switzerland","area":"瑞士","area_code":41,"country":"centralEurope","country_code":2},
        {"area_en":"Austria","area":"奥地利","area_code":43,"country":"centralEurope","country_code":2},
        {"area_en":"United Kingdom","area":"英国","area_code":44,"country":"westEurope","country_code":2},
        {"area_en":"Denmark","area":"丹麦","area_code":45,"country":"northEurope","country_code":2},
        {"area_en":"Sweden","area":"瑞典","area_code":46,"country":"northEurope","country_code":2},
        {"area_en":"Norway","area":"挪威","area_code":47,"country":"northEurope","country_code":2},
        {"area_en":"Poland","area":"波兰","area_code":48,"country":"centralEurope","country_code":2},
        {"area_en":"Germany","area":"德国","area_code":49,"country":"centralEurope","country_code":2},
        {"area_en":"Peru","area":"秘鲁","area_code":51,"country":"southAmerica","country_code":4},
        {"area_en":"Mexico","area":"墨西哥","area_code":52,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Cuba","area":"古巴","area_code":53,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Argentina","area":"阿根廷","area_code":54,"country":"southAmerica","country_code":4},
        {"area_en":"Brazil","area":"巴西","area_code":55,"country":"southAmerica","country_code":4},
        {"area_en":"Chile","area":"智利","area_code":56,"country":"southAmerica","country_code":4},
        {"area_en":"Colombia","area":"哥伦比亚","area_code":57,"country":"southAmerica","country_code":4},
        {"area_en":"Venezuela","area":"委内瑞拉","area_code":58,"country":"southAmerica","country_code":4},
        {"area_en":"Malaysia","area":"马来西亚","area_code":60,"country":"southEastAsia","country_code":1},
        {"area_en":"Australia","area":"澳大利亚","area_code":61,"country":"oceania","country_code":6},
        {"area_en":"Indonesia","area":"印度尼西亚","area_code":62,"country":"southEastAsia","country_code":1},
        {"area_en":"Philippines","area":"菲律宾","area_code":63,"country":"southEastAsia","country_code":1},
        {"area_en":"New Zealand","area":"新西兰","area_code":64,"country":"oceania","country_code":6},
        {"area_en":"Singapore","area":"新加坡","area_code":65,"country":"southEastAsia","country_code":1},
        {"area_en":"Thailand","area":"泰国","area_code":66,"country":"southEastAsia","country_code":1},
        {"area_en":"Japan","area":"日本","area_code":81,"country":"eastAsia","country_code":1},
        {"area_en":"South Korea","area":"韩国","area_code":82,"country":"eastAsia","country_code":1},
        {"area_en":"Vietnam","area":"越南","area_code":84,"country":"southEastAsia","country_code":1},
        {"area_en":"China","area":"中国","area_code":86,"country":"eastAsia","country_code":1},
        {"area_en":"Turkey","area":"土耳其","area_code":90,"country":"westAsia","country_code":1},
        {"area_en":"India","area":"印度","area_code":91,"country":"southAsia","country_code":1},
        {"area_en":"Pakistan","area":"巴基斯坦","area_code":92,"country":"southAsia","country_code":1},
        {"area_en":"Afghanistan","area":"阿富汗","area_code":93,"country":"westAsia","country_code":1},
        {"area_en":"Sri Lanka","area":"斯里兰卡","area_code":94,"country":"southAsia","country_code":1},
        {"area_en":"Myanmar","area":"缅甸","area_code":95,"country":"southEastAsia","country_code":1},
        {"area_en":"Iran","area":"伊朗","area_code":98,"country":"westAsia","country_code":1},
        {"area_en":"South Sudan","area":"苏丹","area_code":211,"country":"eastAfrica","country_code":3},
        {"area_en":"Morocco","area":"摩洛哥","area_code":212,"country":"northAfrica","country_code":3},
        {"area_en":"Western Sahara","area":"西撒哈拉","area_code":212},
        {"area_en":"Algeria","area":"阿尔及利亚","area_code":213,"country":"northAfrica","country_code":3},
        {"area_en":"Tunisia","area":"突尼斯","area_code":216,"country":"northAfrica","country_code":3},
        {"area_en":"Libya","area":"利比亚","area_code":218,"country":"northAfrica","country_code":3},
        {"area_en":"Gambia","area":"冈比亚","area_code":220,"country":"westAfrica","country_code":3},
        {"area_en":"Senegal","area":"塞内加尔","area_code":221,"country":"westAfrica","country_code":3},
        {"area_en":"Mauritania","area":"毛里塔尼亚","area_code":222,"country":"westAfrica","country_code":3},
        {"area_en":"Mali","area":"马里","area_code":223,"country":"westAfrica","country_code":3},
        {"area_en":"Guinea","area":"几内亚","area_code":224,"country":"westAfrica","country_code":3},
        {"area_en":"Ivory Coast","area":"科特迪瓦","area_code":225,"country":"westAfrica","country_code":3},
        {"area_en":"Burkina Faso","area":"布基纳法索","area_code":226,"country":"westAfrica","country_code":3},
        {"area_en":"Niger","area":"尼日尔","area_code":227,"country":"westAfrica","country_code":3},
        {"area_en":"Togo","area":"多哥","area_code":228,"country":"westAfrica","country_code":3},
        {"area_en":"Benin","area":"贝宁","area_code":229,"country":"westAfrica","country_code":3},
        {"area_en":"Mauritius","area":"毛里求斯","area_code":230,"country":"southAfrica","country_code":3},
        {"area_en":"Liberia","area":"利比里亚","area_code":231,"country":"westAfrica","country_code":3},
        {"area_en":"Sierra Leone","area":"塞拉利昂","area_code":232,"country":"westAfrica","country_code":3},
        {"area_en":"Ghana","area":"加纳","area_code":233,"country":"westAfrica","country_code":3},
        {"area_en":"Nigeria","area":"尼日利亚","area_code":234,"country":"westAfrica","country_code":3},
        {"area_en":"Chad","area":"乍得","area_code":235,"country":"centralAfrica","country_code":3},
        {"area_en":"Central African Republic","area":"中非共和国","area_code":236},
        {"area_en":"Cameroon","area":"喀麦隆","area_code":237,"country":"centralAfrica","country_code":3},
        {"area_en":"Sao Tome and Principe","area":"圣多美和普林西比","area_code":239,"country":"centralAfrica","country_code":3},
        {"area_en":"Equatorial Guinea","area":"赤道几内亚","area_code":240,"country":"centralAfrica","country_code":3},
        {"area_en":"Gabon","area":"加蓬","area_code":241,"country":"centralAfrica","country_code":3},
        {"area_en":"Congo","area":"刚果","area_code":242},
        {"area_en":"Zaire","area":"扎伊尔","area_code":243},
        {"area_en":"Angola","area":"安哥拉","area_code":244,"country":"southAfrica","country_code":3},
        {"area_en":"Guinea-Bissau","area":"几内亚比绍","area_code":245,"country":"westAfrica","country_code":3},
        {"area_en":"Ascension","area":"阿森松","area_code":247},
        {"area_en":"Seychelles","area":"塞舌尔","area_code":248,"country":"eastAfrica","country_code":3},
        {"area_en":"Sudan","area":"苏丹","area_code":249,"country":"eastAfrica","country_code":3},
        {"area_en":"Rwanda","area":"卢旺达","area_code":250,"country":"eastAfrica","country_code":3},
        {"area_en":"Ethiopia","area":"埃塞俄比亚","area_code":251,"country":"eastAfrica","country_code":3},
        {"area_en":"Somalia","area":"索马里","area_code":252,"country":"eastAfrica","country_code":3},
        {"area_en":"Djibouti","area":"吉布提","area_code":253,"country":"eastAfrica","country_code":3},
        {"area_en":"Kenya","area":"肯尼亚","area_code":254,"country":"eastAfrica","country_code":3},
        {"area_en":"Tanzania","area":"坦桑尼亚","area_code":255,"country":"eastAfrica","country_code":3},
        {"area_en":"Uganda","area":"乌干达","area_code":256,"country":"eastAfrica","country_code":3},
        {"area_en":"Burundi","area":"布隆迪","area_code":257,"country":"eastAfrica","country_code":3},
        {"area_en":"Mozambique","area":"莫桑比克","area_code":258,"country":"southAfrica","country_code":3},
        {"area_en":"Zambia","area":"赞比亚","area_code":260,"country":"southAfrica","country_code":3},
        {"area_en":"Madagascar","area":"马达加斯加","area_code":261,"country":"southAfrica","country_code":3},
        {"area_en":"Reunion","area":"留尼旺","area_code":262},
        {"area_en":"Zimbabwe","area":"津巴布韦","area_code":263,"country":"southAfrica","country_code":3},
        {"area_en":"Namibia","area":"纳米比亚","area_code":264,"country":"southAfrica","country_code":3},
        {"area_en":"Malawi","area":"马拉维","area_code":265,"country":"southAfrica","country_code":3},
        {"area_en":"Lesotho","area":"莱索托","area_code":266,"country":"southAfrica","country_code":3},
        {"area_en":"Botswana","area":"博茨瓦纳","area_code":267,"country":"southAfrica","country_code":3},
        {"area_en":"Swaziland","area":"斯威士兰","area_code":268,"country":"southAfrica","country_code":3},
        {"area_en":"Barbuda and Antigua","area":"安提瓜和巴布达","area_code":268,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Eritrea","area":"厄立特里亚","area_code":291,"country":"eastAfrica","country_code":3},
        {"area_en":"Kazakstan","area":"哈萨克斯坦","area_code":327,"country":"centralAsia","country_code":1},
        {"area_en":"Gibraltar","area":"直布罗陀","area_code":350},
        {"area_en":"Portugal","area":"葡萄牙","area_code":351,"country":"southEurope","country_code":2},
        {"area_en":"Luxembourg","area":"卢森堡","area_code":352,"country":"westEurope","country_code":2},
        {"area_en":"Ireland","area":"爱尔兰","area_code":353,"country":"westEurope","country_code":2},
        {"area_en":"Iceland","area":"冰岛","area_code":354,"country":"northEurope","country_code":2},
        {"area_en":"Albania","area":"阿尔巴尼亚","area_code":355,"country":"southEurope","country_code":2},
        {"area_en":"Malta","area":"马耳他","area_code":356,"country":"southEurope","country_code":2},
        {"area_en":"Cyprus","area":"塞浦路斯","area_code":357,"country":"westAsia","country_code":1},
        {"area_en":"Finland","area":"芬兰","area_code":358,"country":"northEurope","country_code":2},
        {"area_en":"Bulgaria","area":"保加利亚","area_code":359,"country":"southEurope","country_code":2},
        {"area_en":"Lithuania","area":"立陶宛","area_code":370,"country":"eastEurope","country_code":2},
        {"area_en":"Latvia","area":"拉脱维亚","area_code":371,"country":"eastEurope","country_code":2},
        {"area_en":"Estonia","area":"爱沙尼亚","area_code":372,"country":"eastEurope","country_code":2},
        {"area_en":"Moldova","area":"摩尔多瓦","area_code":373,"country":"eastEurope","country_code":2},
        {"area_en":"Armenia","area":"亚美尼亚","area_code":374,"country":"westAsia","country_code":1},
        {"area_en":"Belarus","area":"白俄罗斯","area_code":375,"country":"eastEurope","country_code":2},
        {"area_en":"Andorra","area":"安道尔共和国","area_code":376},
        {"area_en":"Monaco","area":"摩纳哥","area_code":377,"country":"westEurope","country_code":2},
        {"area_en":"San Marino","area":"圣马力诺","area_code":378,"country":"southEurope","country_code":2},
        {"area_en":"Vatican","area":"梵蒂冈","area_code":379,"country":"southEurope","country_code":2},
        {"area_en":"Ukraine","area":"乌克兰","area_code":380,"country":"eastEurope","country_code":2},
        {"area_en":"Serbia","area":"塞尔维亚","area_code":381,"country":"southEurope","country_code":2},
        {"area_en":"Yugoslavia","area":"南斯拉夫","area_code":381},
        {"area_en":"Croatia","area":"克罗地亚","area_code":385,"country":"southEurope","country_code":2},
        {"area_en":"Slovenia","area":"斯洛文尼亚","area_code":386,"country":"southEurope","country_code":2},
        {"area_en":"Bosnia and Herzegovina","area":"波黑","area_code":387},
        {"area_en":"North Macedonia","area":"北马其顿","area_code":389,"country":"southEurope","country_code":2},
        {"area_en":"Czech Republic","area":"捷克","area_code":420,"country":"centralEurope","country_code":2},
        {"area_en":"Slovakia","area":"斯洛伐克","area_code":421,"country":"centralEurope","country_code":2},
        {"area_en":"Liechtenstein","area":"列支敦士登","area_code":423,"country":"centralEurope","country_code":2},
        {"area_en":"Belize","area":"伯利兹","area_code":501,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Guatemala","area":"危地马拉","area_code":502,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"EI Salvador","area":"萨尔瓦多","area_code":503,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Honduras","area":"洪都拉斯","area_code":504,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Nicaragua","area":"尼加拉瓜","area_code":505,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Costa Rica","area":"哥斯达黎加","area_code":506,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Panama","area":"巴拿马","area_code":507,"country":"centralNorthAmerica","country_code":5},
        {"area_en":"Haiti","area":"海地","area_code":509,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Bolivia","area":"玻利维亚","area_code":591,"country":"southAmerica","country_code":4},
        {"area_en":"Guyana","area":"圭亚那","area_code":592,"country":"southAmerica","country_code":4},
        {"area_en":"Ecuador","area":"厄瓜多尔","area_code":593,"country":"southAmerica","country_code":4},
        {"area_en":"French Guiana","area":"法属圭亚那","area_code":594},
        {"area_en":"Paraguay","area":"巴拉圭","area_code":595,"country":"southAmerica","country_code":4},
        {"area_en":"Martinique","area":"马提尼克","area_code":596},
        {"area_en":"Suriname","area":"苏里南","area_code":597,"country":"southAmerica","country_code":4},
        {"area_en":"Uruguay","area":"乌拉圭","area_code":598,"country":"southAmerica","country_code":4},
        {"area_en":"Netheriands Antilles","area":"荷属安的列斯","area_code":599},
        {"area_en":"Brunei","area":"文莱","area_code":673,"country":"southEastAsia","country_code":1},
        {"area_en":"Nauru","area":"瑙鲁","area_code":674,"country":"oceania","country_code":6},
        {"area_en":"Papua New Cuinea","area":"巴布亚新几内亚","area_code":675,"country":"oceania","country_code":6},
        {"area_en":"Tonga","area":"汤加","area_code":676,"country":"oceania","country_code":6},
        {"area_en":"Solomon Is.","area":"所罗门群岛","area_code":677,"country":"oceania","country_code":6},
        {"area_en":"Fiji","area":"斐济","area_code":679,"country":"oceania","country_code":6},
        {"area_en":"Cook Is.","area":"库克群岛","area_code":682,"country":"oceania","country_code":6},
        {"area_en":"Samoa Eastern","area":"东萨摩亚(美)","area_code":684},
        {"area_en":"Samoa Western","area":"西萨摩亚","area_code":685},
        {"area_en":"French Polynesia","area":"法属玻利尼西亚","area_code":689},
        {"area_en":"North Korea","area":"朝鲜","area_code":850,"country":"eastAsia","country_code":1},
        {"area_en":"Hongkong","area":"香港","area_code":852},
        {"area_en":"Macao","area":"澳门","area_code":853},
        {"area_en":"Kampuchea(Cambodia)","area":"柬埔寨","area_code":855,"country":"southEastAsia","country_code":1},
        {"area_en":"Laos","area":"老挝","area_code":856,"country":"southEastAsia","country_code":1},
        {"area_en":"Bangladesh","area":"孟加拉国","area_code":880,"country":"southAsia","country_code":1},
        {"area_en":"Taiwan","area":"台湾省","area_code":886},
        {"area_en":"Maldives","area":"马尔代夫","area_code":960,"country":"southAsia","country_code":1},
        {"area_en":"Lebanon","area":"黎巴嫩","area_code":961,"country":"westAsia","country_code":1},
        {"area_en":"Jordan","area":"约旦","area_code":962,"country":"westAsia","country_code":1},
        {"area_en":"Syria","area":"叙利亚","area_code":963,"country":"westAsia","country_code":1},
        {"area_en":"Iraq","area":"伊拉克","area_code":964,"country":"westAsia","country_code":1},
        {"area_en":"Kuwait","area":"科威特","area_code":965,"country":"westAsia","country_code":1},
        {"area_en":"Saudi Arabia","area":"沙特阿拉伯","area_code":966,"country":"westAsia","country_code":1},
        {"area_en":"Yemen","area":"也门","area_code":967,"country":"westAsia","country_code":1},
        {"area_en":"Oman","area":"阿曼","area_code":968,"country":"westAsia","country_code":1},
        {"area_en":"Palestine","area":"巴勒斯坦","area_code":970,"country":"westAsia","country_code":1},
        {"area_en":"United Arab Emirates","area":"阿拉伯联合酋长国","area_code":971,"country":"westAsia","country_code":1},
        {"area_en":"Israel","area":"以色列","area_code":972,"country":"westAsia","country_code":1},
        {"area_en":"Bahrain","area":"巴林","area_code":973,"country":"westAsia","country_code":1},
        {"area_en":"Qatar","area":"卡塔尔","area_code":974,"country":"westAsia","country_code":1},
        {"area_en":"Mongolia","area":"蒙古","area_code":976,"country":"eastAsia","country_code":1},
        {"area_en":"Nepal","area":"尼泊尔","area_code":977,"country":"southAsia","country_code":1},
        {"area_en":"Tajikstan","area":"塔吉克斯坦","area_code":992,"country":"centralAsia","country_code":1},
        {"area_en":"Turkmenistan","area":"土库曼斯坦","area_code":993,"country":"centralAsia","country_code":1},
        {"area_en":"Azerbaijan","area":"阿塞拜疆","area_code":994,"country":"westAsia","country_code":1},
        {"area_en":"Georgia","area":"格鲁吉亚","area_code":995,"country":"westAsia","country_code":1},
        {"area_en":"Kyrgyzstan","area":"吉尔吉斯斯坦","area_code":996,"country":"centralAsia","country_code":1},
        {"area_en":"Uzbekistan","area":"乌兹别克斯坦","area_code":998,"country":"centralAsia","country_code":1},
        {"area_en":"Bahamas","area":"巴哈马","area_code":1242,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Barbados","area":"巴巴多斯","area_code":1246,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Anguilla","area":"安圭拉岛","area_code":1264},
        {"area_en":"Antigua and Barbuda","area":"安提瓜和巴布达","area_code":1268,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"CaymanIs.","area":"开曼群岛","area_code":1345},
        {"area_en":"Bermuda Is.","area":"百慕大群岛","area_code":1441},
        {"area_en":"Grenada","area":"格林纳达","area_code":1473,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"MontserratIs","area":"蒙特塞拉特岛","area_code":1664},
        {"area_en":"MarianaIs","area":"马里亚那群岛","area_code":1670},
        {"area_en":"Guam","area":"关岛","area_code":1671},
        {"area_en":"Saint Lueia","area":"圣卢西亚","area_code":1758,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Saint Vincent","area":"圣文森特岛","area_code":1784},
        {"area_en":"PuertoRico","area":"波多黎各","area_code":1787},
        {"area_en":"Trinidad and Tobago","area":"特立尼达和多巴哥","area_code":1809,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Jamaica","area":"牙买加","area_code":1876,"country":"caribbeanNorthAmerica","country_code":5},
        {"area_en":"Dominica Rep.","area":"多米尼加共和国","area_code":1890},
    ]
}

const areaCode = {
    init: init
};


export default areaCode



//////////////////
// WEBPACK FOOTER
// ./core/areaCode.js
// module id = 88
// module chunks = 73