function init() {
  return {
    6011: [
      {
        title: "额定电压",
        title_en: "Rated Voltage",
        category: "Battery",
        range: [36, 43, 48],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "36，43，48",
        unit: "DCV",
        split: 0,
        data: "0",
        length: 1,
      },
      {
        title: "电量满时最大限流值",
        title_en: "Max Limited Current",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "最大限流， 0-100A",
        unit: "A",
        split: 0,
        data: "1",
        length: 1,
      },
      {
        title: "过电压",
        title_en: "Over-voltage",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "DCV",
        split: 0,
        data: "2",
        length: 1,
      },
      {
        title: "欠压",
        title_en: "Under-voltage",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "电机不工作或空转时欠压值，0-100V",
        unit: "DCV",
        split: 0,
        data: "3",
        length: 1,
      },
      {
        title: "骑行动态欠压",
        title_en: "Riding under-voltage",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "DCV",
        split: 0,
        data: "4",
        length: 1,
      },
      {
        title: "欠压恢复电压",
        title_en: "Recovery voltage",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "DCV",
        split: 0,
        data: "5",
        length: 1,
      },
      {
        title: "电池容量",
        title_en: "Battery capacity",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "mAh",
        split: 0,
        data: "7-8",
        length: 2,
      },
      {
        title: "电量不足时最大限流",
        title_en: "Ordinary Limited Current",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "A",
        split: 0,
        data: "9",
        length: 1,
      },
      {
        title: "电流开始衰减时电量值阈值",
        title_en: "Capacity percentage for current begins to decay",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "10",
        length: 1,
      },
      {
        title: "电流开始衰减时电量百分比系数",
        title_en: "Capacity percentage for current begins to decay coefficient",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "11",
        length: 1,
      },
      {
        title: "满电里程数显示",
        title_en: "Full capacity mileage display",
        category: "Battery",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Km",
        split: 0,
        data: "12",
        length: 1,
      },
      {
        title: "传感器类型",
        title_en: "Sensor Type",
        category: "Pedal_sensor",
        range: [0, 1, 2],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-力矩传感器,1-速度传感器,2-仅转把",
        unit: "",
        split: 0,
        data: "13",
        length: 1,
      },
      {
        title: "倒刹功能",
        title_en: "Coaster brake function",
        category: "Pedal_sensor",
        range: [0, 1],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-不支持倒刹,1-支持倒刹",
        unit: "",
        split: 0,
        data: "14",
        length: 1,
      },
      {
        title: "速度码盘齿数",
        title_en: "Speed signal channel number",
        category: "Pedal_sensor",
        range: [1, 2],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "15",
        length: 1,
      },
      {
        title: "速度信号通道数",
        title_en: "Speed signal channel number",
        category: "Pedal_sensor",
        range: [1, 2],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "1-单通道，2-正交双通道",
        unit: "",
        split: 0,
        data: "16",
        length: 1,
      },
      {
        title: "防跟转力矩检查齿数",
        title_en: "Check teeth for heel torque",
        category: "Pedal_sensor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "17",
        length: 1,
      },
      {
        title: "电机类型",
        title_en: "Motor type",
        category: "Motor",
        range: [0, 1, 2],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-轮毂电机，1-中置电机，2-直驱电机(踏板车)",
        unit: "",
        split: 0,
        data: "18",
        length: 1,
      },
      {
        title: "电机极对数",
        title_en: "Motor pole logarithm",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "19",
        length: 1,
      },
      {
        title: "测速磁钢数",
        title_en: "Magnetic steel number for velocity measurement",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "20",
        length: 1,
      },
      {
        title: "温度传感器信号",
        title_en: "Temperature sensor",
        category: "Motor",
        range: [0, 1, 2],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-无,1-10K,2-PT1000",
        unit: "",
        split: 0,
        data: "21",
        length: 1,
      },
      {
        title: "减速比",
        title_en: "Deceleration ratio (multiplied by 0.01)",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "乘以0.01",
        unit: "",
        split: 0,
        data: "22-23",
        length: 2,
      },
      {
        title: "电机机芯最高转速",
        title_en: "Max. speed of rotor",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "不明确或不需要填0",
        unit: "RPM",
        split: 0,
        data: "24-25",
        length: 2,
      },
      {
        title: "D轴电感",
        title_en: "D-axis  inductance",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "不明确或不需要填0",
        unit: "uH",
        split: 0,
        data: "26-27",
        length: 2,
      },
      {
        title: "Q轴电感",
        title_en: "Q-axis  inductance",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "不明确或不需要填0",
        unit: "uH",
        split: 0,
        data: "28-29",
        length: 2,
      },
      {
        title: "相限电阻",
        title_en: "Phase resistance",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "不明确或不需要填0",
        unit: "mΩ",
        split: 0,
        data: "30-31",
        length: 2,
      },
      {
        title: "反电势系数",
        title_en: "Reverse potential coefficient",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "不明确或不需要填0",
        unit: "0.001V/RPM",
        split: 0,
        data: "32-33",
        length: 2,
      },
      {
        title: "转把启动电压",
        title_en: "Throttle start voltage",
        category: "Throttle",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1DCV",
        split: 0,
        data: "34",
        length: 1,
      },
      {
        title: "转把满度电压",
        title_en: "Throttle max. output voltage",
        category: "Throttle",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1DCV",
        split: 0,
        data: "35",
        length: 1,
      },
      {
        title: "转把限速功能",
        title_en: "Speed limit switch function",
        category: "Throttle",
        range: [0, 1],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-不限速，1-限速",
        unit: "",
        split: 0,
        data: "36",
        length: 1,
      },
      {
        title: "启动电流",
        title_en: "Starting current",
        category: "Speed_Sensor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "37",
        length: 1,
      },
      {
        title: "电流加载时间",
        title_en: "Current loading time",
        category: "Speed_Sensor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "100ms",
        split: 0,
        data: "38",
        length: 1,
      },
      {
        title: "电流减载时间",
        title_en: "Current load shedding time",
        category: "Speed_Sensor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "100ms",
        split: 0,
        data: "39",
        length: 1,
      },
      {
        title: "档位1-限流百分比",
        title_en: "Current limit percentage for level 1",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "40",
        length: 1,
      },
      {
        title: "档位2-限流百分比",
        title_en: "Current limit percentage for level 2",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "41",
        length: 1,
      },
      {
        title: "档位3-限流百分比",
        title_en: "Current limit percentage for level 3",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "42",
        length: 1,
      },
      {
        title: "档位4-限流百分比",
        title_en: "Current limit percentage for level 4",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "43",
        length: 1,
      },
      {
        title: "档位5-限流百分比",
        title_en: "Current limit percentage for level 5",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "44",
        length: 1,
      },
      {
        title: "档位6-限流百分比",
        title_en: "Current limit percentage for level 6",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "45",
        length: 1,
      },
      {
        title: "档位7-限流百分比",
        title_en: "Current limit percentage for level 7",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "46",
        length: 1,
      },
      {
        title: "档位8-限流百分比",
        title_en: "Current limit percentage for level 8",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "47",
        length: 1,
      },
      {
        title: "档位9-限流百分比",
        title_en: "Current limit percentage for level 9",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "48",
        length: 1,
      },
      {
        title: "档位1-限速百分比",
        title_en: "Speed limit percentage for level 1",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "49",
        length: 1,
      },
      {
        title: "档位2-限速百分比",
        title_en: "Speed limit percentage for level 2",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "50",
        length: 1,
      },
      {
        title: "档位3-限速百分比",
        title_en: "Speed limit percentage for level 3",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "51",
        length: 1,
      },
      {
        title: "档位4-限速百分比",
        title_en: "Speed limit percentage for level 4",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "52",
        length: 1,
      },
      {
        title: "档位5-限速百分比",
        title_en: "Speed limit percentage for level 5",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "53",
        length: 1,
      },
      {
        title: "档位6-限速百分比",
        title_en: "Speed limit percentage for level 6",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "54",
        length: 1,
      },
      {
        title: "档位7-限速百分比",
        title_en: "Speed limit percentage for level 7",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "55",
        length: 1,
      },
      {
        title: "档位8-限速百分比",
        title_en: "Speed limit percentage for level 8",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "56",
        length: 1,
      },
      {
        title: "档位9-限速百分比",
        title_en: "Speed limit percentage for level 9",
        category: "Level",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "57",
        length: 1,
      },
      {
        title: "有无仪表",
        title_en: "Have or not display",
        category: "System",
        range: [0, 1],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0 有仪表， 1 无仪表",
        unit: "",
        split: 0,
        data: "58",
        length: 1,
      },
      {
        title: "大灯常亮",
        title_en: "Lamps are normally on",
        category: "System",
        range: [0, 1],
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0-随仪表，1-上电常亮",
        unit: "",
        split: 0,
        data: "59",
        length: 1,
      },
      {
        title: "助推速度",
        title_en: "Assist speed",
        category: "System",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "0 无助推功能",
        unit: "",
        split: 0,
        data: "60-61",
        length: 2,
      },
    ],
    6012: [
      {
        title: "启动力矩值-0",
        title_en: "Starting torque value-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "0",
        length: 1,
      },
      {
        title: "启动力矩值-1",
        title_en: "Starting torque value-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "1",
        length: 1,
      },
      {
        title: "启动力矩值-2",
        title_en: "Starting torque value-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "2",
        length: 1,
      },
      {
        title: "启动力矩值-3",
        title_en: "Starting torque value-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "3",
        length: 1,
      },
      {
        title: "启动力矩值-4",
        title_en: "Starting torque value-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "4",
        length: 1,
      },
      {
        title: "启动力矩值-5",
        title_en: "Starting torque value-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "5",
        length: 1,
      },
      {
        title: "满载力矩值-0",
        title_en: "Full load torque value-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "6",
        length: 1,
      },
      {
        title: "满载力矩值-1",
        title_en: "Full load torque value-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "7",
        length: 1,
      },
      {
        title: "满载力矩值-2",
        title_en: "Full load torque value-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "8",
        length: 1,
      },
      {
        title: "满载力矩值-3",
        title_en: "Full load torque value-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "9",
        length: 1,
      },
      {
        title: "满载力矩值-4",
        title_en: "Full load torque value-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "10",
        length: 1,
      },
      {
        title: "满载力矩值-5",
        title_en: "Full load torque value-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "11",
        length: 1,
      },
      {
        title: "返回力矩值-0",
        title_en: "Return torque value-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "12",
        length: 1,
      },
      {
        title: "返回力矩值-1",
        title_en: "Return torque value-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "13",
        length: 1,
      },
      {
        title: "返回力矩值-2",
        title_en: "Return torque value-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "14",
        length: 1,
      },
      {
        title: "返回力矩值-3",
        title_en: "Return torque value-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "15",
        length: 1,
      },
      {
        title: "返回力矩值-4",
        title_en: "Return torque value-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "16",
        length: 1,
      },
      {
        title: "返回力矩值-5",
        title_en: "Return torque value-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "Kg",
        split: 0,
        data: "17",
        length: 1,
      },
      {
        title: "最大电流-0",
        title_en: "Maximum current-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "18",
        length: 1,
      },
      {
        title: "最大电流-1",
        title_en: "Maximum current-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "19",
        length: 1,
      },
      {
        title: "最大电流-2",
        title_en: "Maximum current-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "20",
        length: 1,
      },
      {
        title: "最大电流-3",
        title_en: "Maximum current-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "21",
        length: 1,
      },
      {
        title: "最大电流-4",
        title_en: "Maximum current-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "22",
        length: 1,
      },
      {
        title: "最大电流-5",
        title_en: "Maximum current-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "23",
        length: 1,
      },
      {
        title: "最小电流-0",
        title_en: "Minimum current-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "24",
        length: 1,
      },
      {
        title: "最小电流-1",
        title_en: "Minimum current-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "25",
        length: 1,
      },
      {
        title: "最小电流-2",
        title_en: "Minimum current-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "26",
        length: 1,
      },
      {
        title: "最小电流-3",
        title_en: "Minimum current-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "27",
        length: 1,
      },
      {
        title: "最小电流-4",
        title_en: "Minimum current-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "28",
        length: 1,
      },
      {
        title: "最小电流-5",
        title_en: "Minimum current-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "%",
        split: 0,
        data: "29",
        length: 1,
      },
      {
        title: "力矩衰减时间-0",
        title_en: "Torque attenuation-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "30",
        length: 1,
      },
      {
        title: "力矩衰减时间-1",
        title_en: "Torque attenuation-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "31",
        length: 1,
      },
      {
        title: "力矩衰减时间-2",
        title_en: "Torque attenuation-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "32",
        length: 1,
      },
      {
        title: "力矩衰减时间-3",
        title_en: "Torque attenuation-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "33",
        length: 1,
      },
      {
        title: "力矩衰减时间-4",
        title_en: "Torque attenuation-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "34",
        length: 1,
      },
      {
        title: "力矩衰减时间-5",
        title_en: "Torque attenuation-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "10ms",
        unit: "10ms",
        split: 0,
        data: "35",
        length: 1,
      },
      {
        title: "启动脉冲数-0",
        title_en: "Start pulse number 0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "36",
        length: 1,
      },
      {
        title: "启动脉冲数-1",
        title_en: "Start pulse number 1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "37",
        length: 1,
      },
      {
        title: "启动脉冲数-2",
        title_en: "Start pulse number 2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "38",
        length: 1,
      },
      {
        title: "启动脉冲数-3",
        title_en: "Start pulse number 3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "39",
        length: 1,
      },
      {
        title: "启动脉冲数-4",
        title_en: "Start pulse number 4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "40",
        length: 1,
      },
      {
        title: "启动脉冲数-5",
        title_en: "Start pulse number 5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "41",
        length: 1,
      },
      {
        title: "电流衰减时间-0",
        title_en: "Current decay time 0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "42",
        length: 1,
      },
      {
        title: "电流衰减时间-1",
        title_en: "Current decay time 1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "43",
        length: 1,
      },
      {
        title: "电流衰减时间-2",
        title_en: "Current decay time 2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "44",
        length: 1,
      },
      {
        title: "电流衰减时间-3",
        title_en: "Current decay time 3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "45",
        length: 1,
      },
      {
        title: "电流衰减时间-4",
        title_en: "Current decay time 4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "46",
        length: 1,
      },
      {
        title: "电流衰减时间-5",
        title_en: "Current decay time 5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "5ms",
        unit: "5ms",
        split: 0,
        data: "47",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-0",
        title_en: "Pedal Speed ​​Pulse Max Width-0",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "48",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-1",
        title_en: "Pedal Speed ​​Pulse Max Width-1",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "49",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-2",
        title_en: "Pedal Speed ​​Pulse Max Width-2",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "50",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-3",
        title_en: "Pedal Speed ​​Pulse Max Width-3",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "51",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-4",
        title_en: "Pedal Speed ​​Pulse Max Width-4",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "52",
        length: 1,
      },
      {
        title: "踏板速度脉冲最大宽度-5",
        title_en: "Pedal Speed ​​Pulse Max Width-5",
        category: "Torque",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "2ms",
        unit: "2ms",
        split: 0,
        data: "53",
        length: 1,
      },
      {
        title: "电机降额温度",
        title_en: "Motor temperature safety threshold",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "140",
        unit: "℃",
        split: 0,
        data: "54",
        length: 1,
      },
      {
        title: "电机过热温度",
        title_en: "Motor overheating temperature",
        category: "Motor",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "℃",
        split: 0,
        data: "55",
        length: 1,
      },
    ],
    6017: [
      {
        title: "电流加载初值",
        title_en: "Current loading initial value",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "ms",
        split: 0,
        data: "48",
        length: 1,
      },
      {
        title: "电流加载与踏频关系K1",
        title_en: "The relationship between current loading and cadence K1",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "ms",
        split: 0,
        data: "49",
        length: 1,
      },
      {
        title: "电流衰减与踏频关系K2",
        title_en: "The relationship between current attenuation and cadence K2",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "ms",
        split: 0,
        data: "50",
        length: 1,
      },
      {
        title: "电流衰减与踏频关系K3",
        title_en: "The relationship between current attenuation and cadence K3",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "ms",
        split: 0,
        data: "51",
        length: 1,
      },
      {
        title: "电流衰减与踏频关系K4",
        title_en: "The relationship between current attenuation and cadence K4",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "ms",
        split: 0,
        data: "52",
        length: 1,
      },
      {
        title: "力矩启动值常数",
        title_en: "Torque pickup value constant",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "mV",
        split: 0,
        data: "53",
        length: 1,
      },
      {
        title: "力矩启动与踏频关系K5",
        title_en: "The relationship between torque start and cadence K5",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "mV",
        split: 0,
        data: "54-55",
        length: 2,
      },
      {
        title: "力矩最小值常数",
        title_en: "Moment Min Constant",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "mV",
        split: 0,
        data: "56-57",
        length: 2,
      },
      {
        title: "力矩最小值与踏频关系K6",
        title_en: "The relationship between the minimum torque and cadence K6",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "mV",
        split: 0,
        data: "58-59",
        length: 2,
      },
      {
        title: "力矩放大倍数",
        title_en: "torque magnification",
        category: "Mountain",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "",
        split: 0,
        data: "60-61",
        length: 2,
      },
    ],
    6018: [
      {
        title: "限速限流1电池总容量",
        title_en: "Speed ​​limit current limit 1 total battery capacity",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Ah",
        split: 0,
        data: "0-1",
        length: 2,
      },
      {
        title: "限速限流2电池总容量",
        title_en: "Speed ​​limit current limit 2 total battery capacity",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Ah",
        split: 0,
        data: "2-3",
        length: 2,
      },
      {
        title: "限速1",
        title_en: "speed limit 1",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Km/H",
        split: 0,
        data: "4-5",
        length: 2,
      },
      {
        title: "限流1",
        title_en: "Current limit 1",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Ah",
        split: 0,
        data: "6-7",
        length: 2,
      },
      {
        title: "限速2",
        title_en: "speed limit 2",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Km/H",
        split: 0,
        data: "8-9",
        length: 2,
      },
      {
        title: "限流2",
        title_en: "Limit 2",
        category: "DIY",
        range: 0,
        read_value: "",
        standard_value: "",
        set_value: "",
        description: "",
        unit: "0.1Ah",
        split: 0,
        data: "10-11",
        length: 2,
      },
    ],
  };
}

export default init();

//////////////////
// WEBPACK FOOTER
// ./core/ctrlParams.js
// module id = 1110
// module chunks = 73
