/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_oc_pal_0.h"

/*******************************************************************************
 * oc_pal_0 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'oc_pal_0'
- type: 'ocPal'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'oc_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM_0'
- config_sets:
  - oc_pal:
    - ocPalInstanceCfg:
      - name: 'oc_pal'
      - readOnly: 'false'
      - instType: 'OC_INST_TYPE_FTM'
    - ocPalClockConfig:
      - ocPalInputClkSrc: 'FTM_CLOCK_SOURCE_EXTERNALCLK'
      - ocPalPrescaler: 'FTM_CLOCK_DIVID_BY_128'
    - ocPalConfig:
      - ocPalMaxCountValue: '62500'
      - ocPalChnConfigList:
        - 0:
          - hwChannelId: '0U'
          - chMode: 'OC_TOGGLE_ON_MATCH'
          - comparedValue: '50000'
          - channelCallbacks: 'oc_pal1_channel_callBack0'
          - channelCallbackParams: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
/*! @brief PAL instance information */
oc_instance_t oc_pal_instance_0 = { OC_INST_TYPE_FTM, 0U };

/*! @brief Channel configuration array */
oc_output_ch_param_t oc_pal_instance_0_ChnConfig[1] =
{
    /* Channel configuration 0 */
    {
        .hwChannelId           = 0U, /* Hardware channel ID */
        .chMode                = OC_TOGGLE_ON_MATCH, /* Output Compare mode */
        .comparedValue         = 50000U, /* compared value */
        .channelExtension      = NULL, /* channel extension */
        .channelCallbackParams = NULL, /* callback parameter */
        .channelCallbacks      = oc_pal1_channel_callBack0 /* Callback */
    }
};

/*! @brief IP specific extension configuration */
extension_ftm_for_oc_t  oc_pal_instance_0_ftmExtension =
{
    .maxCountValue        = 62500, /* Max count value of output compared counter */
    .ftmClockSource       = FTM_CLOCK_SOURCE_EXTERNALCLK, /* The clock source */
    .ftmPrescaler         = FTM_CLOCK_DIVID_BY_128 /* The prescaler for output compare counter */
};

/*! @brief Output compare configuration */
oc_config_t  oc_pal_instance_0_InitConfig =
{
    .nNumChannels   = 1U,
    .outputChConfig = oc_pal_instance_0_ChnConfig,
    .extension      = &oc_pal_instance_0_ftmExtension
};


