/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef oc_pal_0_H
#define oc_pal_0_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "oc_pal.h"
#include <stddef.h>

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
/*! @brief PAL instance information */

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
extern oc_instance_t oc_pal_instance_0;

/*! @brief Channels configuration structure for oc_pal_instance_0*/
extern oc_output_ch_param_t  oc_pal_instance_0_ChnConfig[1];

/*! @brief The extension structure for the oc_pal_instance_0 */
extern extension_ftm_for_oc_t oc_pal_instance_0_ftmExtension;

/*! @brief Global configuration of oc_pal_instance_0 */
extern oc_config_t oc_pal_instance_0_InitConfig;

/*! @brief Callback function of channel configuration 0 */
extern void oc_pal1_channel_callBack0(oc_event_t event, void * userData);



#endif /* oc_pal_0_H */
