/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef wdg_pal_1_H
#define wdg_pal_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "wdg_pal.h"
#include "wdg_pal_mapping.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define WDG_PAL_1_NUM_OF_USER_CFG  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* Structure storing PAL instance information */
extern const wdg_instance_t wdg_pal_1_Instance;

/* User Configurations */
extern const wdg_config_t wdg_pal_1_Config0;



#endif /* wdg_pal_1_H */
