/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef eim_config_1_H
#define eim_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "eim_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/* EIM instance number configured */
#define INST_EIM_CONFIG_1  (0U)

/* Number of configured channels for EIM instances */
#define EIM_CHANNEL_COUNT0  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User channel configuration structure list configuration */

/* User configuration 0 */
extern const eim_user_channel_config_t eim_InitConfig0[EIM_CHANNEL_COUNT0];



#endif /* eim_config_1_H */
