/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_eim_config_1.h"

/*******************************************************************************
 * eim_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'eim_config_1'
- type: 'eim_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'eim'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'EIM'
- config_sets:
  - eim:
    - eimConfig:
      - 0:
        - name: 'eim_InitConfig0'
        - readOnly: 'true'
        - channelConfig:
          - 0:
            - channel: '0'
            - checkBitMask: '0'
            - dataMask: '1'
            - dataMask1: '0'
            - enable: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* Channel configurations */
const eim_user_channel_config_t eim_InitConfig0[EIM_CHANNEL_COUNT0] =
{
    /* Channel configuration 0 */
    {
        .channel = 0U,
        .checkBitMask = 0U,
        .dataMask = 1U,
        .enable = true
    }
};


