/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef flash_FTFC_H
#define flash_FTFC_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * There are global macros defined to be used by the integrator and another one used as include guard.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "flash_driver.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* User configuration structures */

/* User configuration 0 */
extern const flash_user_config_t Flash_InitConfig0;



#endif /* flash_FTFC_H */
