/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef sbc_uja116x_H
#define sbc_uja116x_H

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "sbc_uja116x_driver.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* SBC UJA116xA Configuration 0. */
extern const sbc_int_config_t sbc_uja116x_InitConfig0;




#endif /* sbc_uja116x_H */
