/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef I2C_PAL_CFG_H
#define I2C_PAL_CFG_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define I2C_OVER_FLEXIO  1
#define I2C_OVER_LPI2C  1

#define NO_OF_FLEXIO_INSTS_FOR_I2C  1
#define NO_OF_LPI2C_INSTS_FOR_I2C  1

#endif /* I2C_PAL_CFG_H */

