/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef i2c_pal_config_2_H
#define i2c_pal_config_2_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "i2c_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* PAL instance information */
extern i2c_instance_t flexio_instance;

/* Master module configurations */
extern i2c_master_t i2c_pal_flexio_MasterConfig0;



#endif /* i2c_pal_config_2_H */
