/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef i2c_pal_config_1_H
#define i2c_pal_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "i2c_pal.h"

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* PAL instance information */
extern i2c_instance_t lpi2c0_instance;

/* Slave module configurations */
extern i2c_slave_t i2c_pal_lpi2c0_SlaveConfig0;

/* Define external callbacks for slave devices */
extern void i2c1_SlaveCallback0(i2c_slave_event_t slaveEvent,void *userData);



#endif /* i2c_pal_config_1_H */
