/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef flexio_uart_TX_H
#define flexio_uart_TX_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "flexio_uart_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_FLEXIO_UART_TX  (0U)

/* External declaration of FlexioUART configuration structure */
extern const flexio_uart_user_config_t flexio_uart_TX_Config0;

/* External declaration of user callback function */
extern void flexio_uart_TX_Callback0(void *driverState, uart_event_t event, void *userData);



#endif /* flexio_uart_TX_H */
