/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_flexTimer_ic_1.h"

/*******************************************************************************
 * flexTimer_ic_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'flexTimer_ic_1'
- type: 'flexTimer_ic'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'ftm_ic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM_1'
- config_sets:
  - ftm_ic:
    - totalConfiguration:
      - ftmUserConfig:
        - ClockSource: 'FTM_CLOCK_SOURCE_SYSTEMCLK'
        - ClockSourcePrescaler: '1'
        - DebugMode: 'FTM_BDM_MODE_11'
        - TimerOverInterrupt: 'false'
        - InitializationTrigger: 'false'
      - icConfiguration:
        - numofChannel: '1'
        - maxCountVal: '65535'
        - arrayicConfig:
          - 0:
            - configName: 'flexTimer_ic_1_ChannelConfig0'
            - hwID: '0'
            - operationMode: 'FTM_SIGNAL_MEASUREMENT'
            - edgeDetectMode: 'FTM_RISING_EDGE'
            - measureMode: 'FTM_FALLING_EDGE_PERIOD_MEASUREMENT'
            - continousMode: 'true'
            - inputCaptureFilter: 'false'
            - inputCaptureFilterValue: '0'
            - callback: 'NULL'
            - callbackParameter: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* Global configuration of flexTimer_ic_1 InitConfig */
ftm_user_config_t flexTimer_ic_1_InitConfig =
{
    {
        true,    /* Software trigger state */
        false,  /* Hardware trigger 1 state */
        false,  /* Hardware trigger 2 state */
        false,  /* Hardware trigger 3 state */
        false, /* Max loading point state */
        false, /* Min loading point state */
        FTM_SYSTEM_CLOCK, /* Update mode for INVCTRL register */
        FTM_SYSTEM_CLOCK, /* Update mode for SWOCTRL register */
        FTM_SYSTEM_CLOCK, /* Update mode for OUTMASK register */
        FTM_SYSTEM_CLOCK, /* Update mode for CNTIN register */
        false, /* Automatic clear of the trigger */
        FTM_UPDATE_NOW, /* Synchronization point */
    },
        FTM_MODE_INPUT_CAPTURE, /* Mode of operation for FTM */
        FTM_CLOCK_DIVID_BY_1, /* FTM clock prescaler */
        FTM_CLOCK_SOURCE_SYSTEMCLK,   /* FTM clock source */
        FTM_BDM_MODE_11, /* FTM debug mode */
        false,    /* Interrupt state */
        false     /* Initialization trigger */
};

/* Input capture configuration for flexTimer_ic_1 */
ftm_input_param_t flexTimer_ic_1_InputCaptureConfig =
{
    1U, /* Number of channel configurations */
    65535U, /* Maximum count value */
    flexTimer_ic_1_InputCaptureChannelConfig /* Channels configuration*/
};

/* Channels configuration structure for flexTimer_ic_1 input capture */
ftm_input_ch_param_t flexTimer_ic_1_InputCaptureChannelConfig[1] =
{
    {
        0U, /* Channel id */
        FTM_SIGNAL_MEASUREMENT, /* Input capture operation mode */
        FTM_RISING_EDGE, /* Edge alignment mode */
        FTM_FALLING_EDGE_PERIOD_MEASUREMENT, /* Signal measurement operation type */
        0U, /* Filter value */
        false, /* Filter state (enabled/disabled) */
        true, /* Continuous measurement state */
        NULL, /* Vector of callbacks  parameters for channels events */
        NULL /* Vector of callbacks for channels events */
    }
};


