/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef ic_pal_1_H
#define ic_pal_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "ic_pal.h"
#include <stddef.h>

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
/*! @brief PAL instance information */

/*******************************************************************************
 * Global variables 
 ******************************************************************************/
extern ic_instance_t ic_pal_1_instanceConfig;

/* Channels configuration structure for ic_pal_1*/
extern ic_input_ch_param_t  ic_pal_1_ChnConfig[1];

/* The extension structure for the ic_pal_1 */
extern extension_ftm_for_ic_t ic_pal_1_ftmExtension;

/* The channel extension structure for ic_pal_1 */
extern channel_extension_ftm_for_ic_t ic_pal_1_ftmChnExtension0;

/* Global configuration of ic_pal_1 */
extern ic_config_t ic_pal_1_InitConfig;



#endif /* ic_pal_1_H */
