/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef ADC_PAL_CFG_H
#define ADC_PAL_CFG_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define ADC_PAL_S32K1xx /* Define for selecting one of the ADC PAL type to be used */  
#define ADC_PAL_MAX_NUM_HW_GROUPS_EN  1u /* Define the maximum number of HW triggered groups which may be enabled simultaneously */


#endif /* ADC_PAL_CFG_H */

