/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef adc_pal_1_H
#define adc_pal_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "adc_pal.h"
#include <stddef.h>

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/*! @brief PAL instance information */
extern const adc_instance_t adc_pal_1_instance;

/*! @brief configuration structure */
extern const adc_config_t adc_pal_1_config;

/*! @brief array of conversion groups */
extern const adc_group_config_t adc_pal_1_groupArray[3u];

/*! @brief group 0: input channels array */
extern adc_input_chan_t adc_pal_1_channelsArray0[4u];
/*! @brief group 0: results buffer */
extern uint16_t adc_pal_1_results0[1u * 4u];
/*! @brief group 0: callback function */
void adc_pal_1_callback0(const adc_callback_info_t * const callbackInfo, void * userData);

/*! @brief group 1: input channels array */
extern adc_input_chan_t adc_pal_1_channelsArray1[1u];
/*! @brief group 1: results buffer */
extern uint16_t adc_pal_1_results1[1u * 1u];

/*! @brief group 2: input channels array */
extern adc_input_chan_t adc_pal_1_channelsArray2[5u];
/*! @brief group 2: results buffer */
extern uint16_t adc_pal_1_results2[1u * 5u];
/*! @brief group 2: callback function */
void adc_pal_1_callback2(const adc_callback_info_t * const callbackInfo, void * userData);



#endif /* adc_pal_1_H */
