/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_linstack_config.h"

/*******************************************************************************
 * linstack_config initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'linstack_config'
- type: 'linstack_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'linstack'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - linstack:
    - linstackCfg:
      - RefNetworkConfig:
        - UseTransportLayer: 'true'
        - SupportDiagnoticService: 'true'
        - TimeOutUnit: '500'
        - InterleaveTimeOut: '1000'
        - ArrListOfNetwork:
          - 0:
            - RefLinDriverConfig:
              - LinDrvLinDriver: 'LPUART_0'
              - LinDrvLinConfig: 'lin0_InitConfig0'
              - LinDrvDevice: 'LPUART_0'
              - LinDrvBaudRateConfig: '19200'
              - LinDrvNodeFunc: 'SLAVE'
              - LinDrvAutobaud: 'true'
              - LinDrvIntCallback: 'lin0TimerGetTimeIntervalCallback0'
              - LinDrvPidType: 'Enhanced'
              - LinDrvPidClassicChecksum: ''
            - RefNetworkDetail:
              - NetworkName: 'LI0'
              - IsLDFAbsolutePath: 'false'
              - LDFRelativePath: 'src/LIN21_Example.ldf'
              - ProtocolVersion: '2.1'
              - RefNodeName: 'Motor1'
              - NodeProtocol: '2.x'
              - RefDiagClass: 'Class1'
              - IdleTimeout: '5'
              - MaxMessageLength: '6'
              - ArrListOfSr:
                - 0:
                  - SlaveName: 'Motor1'
                  - Sr0: '0x1'
                  - Sr1: '0x1'
                  - Sr2: '0x1'
                  - Sr3: '0x1'
                - 1:
                  - SlaveName: 'Motor2'
                  - Sr0: '0x1'
                  - Sr1: '0x1'
                  - Sr2: '0x1'
                  - Sr3: '0x1'
            - RefSupportedService:
              - ServiceAssignNAD: 'false'
              - ServiceAssignFrameIdentifier: 'false'
              - ServiceReadByIdentifier: 'true'
              - ServiceConditionalChangeNAD: 'false'
              - ServiceDataDump: 'false'
              - ServiceSaveConfiguration: 'false'
              - ServiceAssignFrameIdenRange: 'true'
              - ServiceReadDataByIdentifier: 'false'
              - ServiceWriteDataByIdentifier: 'false'
              - ServiceSessionControl: 'false'
              - ServiceIOControlByIdentifier: 'false'
              - ServiceFaultMemoryRead: 'false'
              - ServiceFaultMemoryClear: 'false'
              - ServiceTargetReset: 'false'
              - SupportSID: 'false'
              - ArrListOfSIDs: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.3, Global typedef not referenced
 * Variable is referenced in a different file by the user.
 *
 */
typedef int make_iso_compilers_happy;

