/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef mpu_pal_config_1_H
#define mpu_pal_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.1, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.2, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.4, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.5, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "stddef.h"
#include "mpu_pal.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/* Region configuration count */
#define MPU_PAL_CONFIG_1_REGION_CFG_CNT0  (5U)

/* User configuration count */
#define MPU_PAL_CONFIG_1_USER_CFG_CNT  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/*******************************************************************************
 * Memory instances
 *******************************************************************************/
extern const mpu_instance_t mpu_pal_config_1_Instance;


/*
 * User configurations
 */
/* Configuration 0 */
extern const mpu_region_config_t mpu_pal_config_1_RegionConfig0[MPU_PAL_CONFIG_1_REGION_CFG_CNT0];

/*******************************************************************************
 * Domain configurations
 *******************************************************************************/
/* Domain Configuration 0 */
extern const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig0[FEATURE_MPU_MASTER_COUNT];
/* Domain Configuration 1 */
extern const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig1[FEATURE_MPU_MASTER_COUNT];
/* Domain Configuration 2 */
extern const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig2[FEATURE_MPU_MASTER_COUNT];
/* Domain Configuration 3 */
extern const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig3[FEATURE_MPU_MASTER_COUNT];



#endif /* mpu_pal_config_1_H */
