/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_mpu_pal_config_1.h"

/*******************************************************************************
 * mpu_pal_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'mpu_pal_config_1'
- type: 'mpu_pal_config'
- mode: 'mpu_pal_basic_s32k'
- custom_name_enabled: 'false'
- type_id: 'mpu_pal'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MPU'
- config_sets:
  - mpu_pal_s32k:
    - mpu_pal_Configuration:
      - mpu_pal_UserConfig:
        - 0:
          - name: 'mpu_pal_config_1_RegionConfig0'
          - readOnly: 'true'
          - mpu_pal_RegionConfig:
            - 0:
              - startAddr: '0x0'
              - endAddr: '0xFFFFFFFF'
              - masterAccRight: 'mpu_pal_config_1_AccessRightConfig0'
              - processIdentifier: '0x0'
              - processIdMask: '0x0'
            - 1:
              - startAddr: '0x0'
              - endAddr: '0x3FEFF'
              - masterAccRight: 'mpu_pal_config_1_AccessRightConfig1'
              - processIdentifier: '0x0'
              - processIdMask: '0x0'
            - 2:
              - startAddr: '0x3FF00'
              - endAddr: '0x3FF1F'
              - masterAccRight: 'mpu_pal_config_1_AccessRightConfig2'
              - processIdentifier: '0x0'
              - processIdMask: '0x0'
            - 3:
              - startAddr: '0x3FF00'
              - endAddr: '0x3FF1F'
              - masterAccRight: 'mpu_pal_config_1_AccessRightConfig3'
              - processIdentifier: '0x0'
              - processIdMask: '0x0'
            - 4:
              - startAddr: '0x3FF20'
              - endAddr: '0xFFFFFFFF'
              - masterAccRight: 'mpu_pal_config_1_AccessRightConfig1'
              - processIdentifier: '0x0'
              - processIdMask: '0x0'
      - mpu_pal_MasterConfig:
        - 0:
          - name: 'mpu_pal_config_1_AccessRightConfig0'
          - readOnly: 'true'
          - mpu_pal_Master:
            - 0:
              - masterNum: 'FEATURE_MPU_MASTER_CORE'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_NONE'
              - pidEnable: 'false'
            - 1:
              - masterNum: 'FEATURE_MPU_MASTER_DEBUGGER'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
            - 2:
              - masterNum: 'FEATURE_MPU_MASTER_DMA'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
        - 1:
          - name: 'mpu_pal_config_1_AccessRightConfig1'
          - readOnly: 'true'
          - mpu_pal_Master:
            - 0:
              - masterNum: 'FEATURE_MPU_MASTER_CORE'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
            - 1:
              - masterNum: 'FEATURE_MPU_MASTER_DEBUGGER'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
            - 2:
              - masterNum: 'FEATURE_MPU_MASTER_DMA'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
        - 2:
          - name: 'mpu_pal_config_1_AccessRightConfig2'
          - readOnly: 'true'
          - mpu_pal_Master:
            - 0:
              - masterNum: 'FEATURE_MPU_MASTER_CORE'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_WX'
              - pidEnable: 'false'
            - 1:
              - masterNum: 'FEATURE_MPU_MASTER_DEBUGGER'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
            - 2:
              - masterNum: 'FEATURE_MPU_MASTER_DMA'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
        - 3:
          - name: 'mpu_pal_config_1_AccessRightConfig3'
          - readOnly: 'true'
          - mpu_pal_Master:
            - 0:
              - masterNum: 'FEATURE_MPU_MASTER_CORE'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_R'
              - pidEnable: 'false'
            - 1:
              - masterNum: 'FEATURE_MPU_MASTER_DEBUGGER'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
            - 2:
              - masterNum: 'FEATURE_MPU_MASTER_DMA'
              - supervisorAccessRight: 'MPU_SUPERVISOR'
              - userAccessRight: 'USER_RWX'
              - pidEnable: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.1, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.2, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.4, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.5, identifier clash.
 * The supported compilers use more than 31 significant characters for identifiers.
 *
 */

/*******************************************************************************
 * Memory instances
 *******************************************************************************/

const mpu_instance_t mpu_pal_config_1_Instance = {
    .instType = MPU_INST_TYPE_MPU,
    .instIdx = 0U
};
/*******************************************************************************
 * Domain configurations
 *******************************************************************************/

/* Domain Configuration 0 */
const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig0[] = {
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_NONE
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    }
};

/* Domain Configuration 1 */
const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig1[] = {
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    }
};

/* Domain Configuration 2 */
const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig2[] = {
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_WX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    }
};

/* Domain Configuration 3 */
const mpu_master_access_permission_t mpu_pal_config_1_AccessRightConfig3[] = {
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_R
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    },
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_RWX
    }
};

/*******************************************************************************
 * User configurations
 *******************************************************************************/

/* Configuration 0 */
const mpu_region_config_t mpu_pal_config_1_RegionConfig0[] = {
    /* Region number 0 */
    {
        .startAddr     = 0x0U,
        .endAddr    = 0xFFFFFFFFU,
        .masterAccRight  = mpu_pal_config_1_AccessRightConfig0,
        .processIdEnable   = 0x0U,
        .processIdentifier   = 0x0U,
        .processIdMask   = 0x0U,
    },
    /* Region number 1 */
    {
        .startAddr     = 0x0U,
        .endAddr    = 0x3FEFFU,
        .masterAccRight  = mpu_pal_config_1_AccessRightConfig1,
        .processIdEnable   = 0x0U,
        .processIdentifier   = 0x0U,
        .processIdMask   = 0x0U,
    },
    /* Region number 2 */
    {
        .startAddr     = 0x3FF00U,
        .endAddr    = 0x3FF1FU,
        .masterAccRight  = mpu_pal_config_1_AccessRightConfig2,
        .processIdEnable   = 0x0U,
        .processIdentifier   = 0x0U,
        .processIdMask   = 0x0U,
    },
    /* Region number 3 */
    {
        .startAddr     = 0x3FF00U,
        .endAddr    = 0x3FF1FU,
        .masterAccRight  = mpu_pal_config_1_AccessRightConfig3,
        .processIdEnable   = 0x0U,
        .processIdentifier   = 0x0U,
        .processIdMask   = 0x0U,
    },
    /* Region number 4 */
    {
        .startAddr     = 0x3FF20U,
        .endAddr    = 0xFFFFFFFFU,
        .masterAccRight  = mpu_pal_config_1_AccessRightConfig1,
        .processIdEnable   = 0x0U,
        .processIdentifier   = 0x0U,
        .processIdMask   = 0x0U,
    }
};

