/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_trgmux_1.h"

/*******************************************************************************
 * trgmux_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'trgmux_1'
- type: 'trgmux_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'trgmux'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TRGMUX'
- config_sets:
  - trgmux:
    - trgmuxCfg:
      - 0:
        - name: 'trgmux1_InitConfig0'
        - readonly: 'true'
        - mapping_cfg:
          - 0:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_TRGMUX_IN10'
            - targetModule: 'TRGMUX_TARGET_MODULE_LPIT_TRG_CH0'
            - lockreg: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
const trgmux_inout_mapping_config_t trgmux_InOutMappingConfig0[TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0] =
{
    {TRGMUX_TRIG_SOURCE_TRGMUX_IN10, TRGMUX_TARGET_MODULE_LPIT_TRG_CH0, false},
};


/*! trgmux configuration structure */
const trgmux_user_config_t trgmux1_InitConfig0 = {
    .numInOutMappingConfigs = TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0,
    .inOutMappingConfig     = trgmux_InOutMappingConfig0,
};



