/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef trgmux_1_H
#define trgmux_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "trgmux_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_TRGMUX  (0U)
#define TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/*! @brief Declaration of InOut Mapping configuration */
extern const trgmux_inout_mapping_config_t trgmux_InOutMappingConfig0[TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0];

/*! @brief Configuration declaration */
extern const trgmux_user_config_t trgmux1_InitConfig0;



#endif /* trgmux_1_H */
