/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef SDK_PROJECT_CONFIG_H_
#define SDK_PROJECT_CONFIG_H_


#endif /* SDK_PROJECT_CONFIG_H_ */
