/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef LPTMR_0_H
#define LPTMR_0_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "lptmr_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_LPTMR_0  (0U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/* LPTMR Configuration 0 */
extern const lptmr_config_t LPTMR0_config0;



#endif /* LPTMR_0_H */
