/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: fb67a0f7-8633-457d-811c-6f759a193676
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_flexcan_config_1.h"

/*******************************************************************************
 * flexcan_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'flexcan_config_1'
- type: 'flexcan_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'flexcan'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CAN0'
- config_sets:
  - flexcan:
    - flexcanCfg:
      - name: 'flexcanInitConfig0'
      - readonly: 'false'
      - flexcan_cfg_flexcanMode: 'FLEXCAN_NORMAL_MODE'
      - flexcan_cfg_fd_enable: 'true'
      - flexcan_cfg_payload: 'FLEXCAN_PAYLOAD_SIZE_16'
      - flexcan_cfg_max_num_mb: '16'
      - flexcan_cfg_num_id_filters: 'FLEXCAN_RX_FIFO_ID_FILTERS_8'
      - flexcan_cfg_is_rx_fifo_needed: 'false'
      - flexcan_cfg_transfer_type: 'FLEXCAN_RXFIFO_USING_INTERRUPTS'
      - flexcan_cfg_rxFifoDMAChannel: '0'
      - flexcan_cfg_pe_clock: 'FLEXCAN_CLK_SOURCE_OSC'
      - flexcan_bitrate2ts: 'true'
      - flexcan_cfg_time_segments2:
        - flexcan_cfg_bitrate:
          - flexcan_cfg_rJumpwidth: '1'
          - input_nominal_bitrate: '500'
          - input_nominal_sampling: '87.5'
        - flexcan_cfg_bitrate_cbt:
          - flexcan_cfg_rJumpwidth: '1'
          - input_data_bitrate: '1000'
          - input_data_sampling: '87.5'
    - flexcanPN:
      - pnOn: 'false'
    - flexcan_state_name: 'flexcanState0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

flexcan_state_t flexcanState0;

flexcan_user_config_t flexcanInitConfig0 = {
  .flexcanMode = FLEXCAN_NORMAL_MODE,
  .fd_enable = true,
  .payload = FLEXCAN_PAYLOAD_SIZE_16,
  .max_num_mb = 16UL,
  .num_id_filters = FLEXCAN_RX_FIFO_ID_FILTERS_8,
  .is_rx_fifo_needed = false,
  .transfer_type = FLEXCAN_RXFIFO_USING_INTERRUPTS,
  .rxFifoDMAChannel = 0U,
  .pe_clock = FLEXCAN_CLK_SOURCE_OSC,
  .bitrate = {
    .propSeg = 7UL,
    .phaseSeg1 = 4UL,
    .phaseSeg2 = 1UL,
    .preDivider = 0UL,
    .rJumpwidth = 1UL
  },
  .bitrate_cbt = {
    .propSeg = 3UL,
    .phaseSeg1 = 1UL,
    .phaseSeg2 = 1UL,
    .preDivider = 0UL,
    .rJumpwidth = 1UL
  }
};


