/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef flexcan_config_1_H
#define flexcan_config_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "flexcan_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_FLEXCAN_CONFIG_1  (0U)

extern flexcan_state_t flexcanState0;

extern flexcan_user_config_t flexcanInitConfig0;



#endif /* flexcan_config_1_H */
