/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: S32K142
package_id: S32K142_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_402
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 90343aac-244f-457d-8992-f8671b852783
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_lpi2c_config_1.h"

/*******************************************************************************
 * lpi2c_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lpi2c_config_1'
- type: 'lpi2c_config'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpi2c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C0'
- config_sets:
  - lpi2c:
    - masterConfigurationLPI2C:
      - 0:
        - name: 'lpi2c0_MasterConfig0'
        - readonly: 'false'
        - lpi2c_master_cfg_slaveAddress: '0x32'
        - lpi2c_master_cfg_is10bitAddr: 'false'
        - lpi2c_master_cfg_operatingMode: 'LPI2C_FAST_MODE'
        - lpi2c_master_cfg_baudRate: '400000'
        - lpi2c_master_cfg_transferType: 'LPI2C_USING_INTERRUPTS'
        - lpi2c_master_cfg_dmaChannel: '0'
        - lpi2c_master_cfg_masterCallback: 'NULL'
        - lpi2c_master_cfg_callbackParam: 'NULL'
    - slaveConfigurationLPI2C: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

lpi2c_master_user_config_t lpi2c0_MasterConfig0 = {
  .slaveAddress = 50U,
  .is10bitAddr = false,
  .operatingMode = LPI2C_FAST_MODE,
  .baudRate = 400000UL,
  .transferType = LPI2C_USING_INTERRUPTS,
  .dmaChannel = 0U,
  .masterCallback = NULL,
  .callbackParam = NULL
};


