/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef MPU_H
#define MPU_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "mpu_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/*! @brief Device instance number */
#define MPU_INST  (0U)

/*! @brief Number of region in user configuration */
#define MPU_NUM_OF_REGION_CFG0  (5U)

/*! @brief Number of user configuration */
#define MPU_NUM_OF_USER_CFG  (1U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/*! @brief User configuration */
extern const mpu_user_config_t MPU_Cfg0[MPU_NUM_OF_REGION_CFG0];

/*! @brief Master access rights */
extern const mpu_master_access_right_t AccessRightConfig0[FEATURE_MPU_MASTER_COUNT];
extern const mpu_master_access_right_t AccessRightConfig1[FEATURE_MPU_MASTER_COUNT];
extern const mpu_master_access_right_t AccessRightConfig2[FEATURE_MPU_MASTER_COUNT];
extern const mpu_master_access_right_t AccessRightConfig3[FEATURE_MPU_MASTER_COUNT];



#endif /* MPU_H */
