/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef flexio_spi2_H
#define flexio_spi2_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "flexio_spi_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_FLEXIO_SPI2  (0U)

/* External declaration of FlexioSPI master configuration structure */
extern const flexio_spi_master_user_config_t flexio_spi2_MasterConfig0;

/* External declaration of FlexioSPI slave configuration structure */
extern const flexio_spi_slave_user_config_t flexio_spi2_SlaveConfig0;



#endif /* flexio_spi2_H */
