/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef SDK_PROJECT_CONFIG_H_
#define SDK_PROJECT_CONFIG_H_


/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/* Include header files for all configured components */
#include "clock_config.h"
#include "pin_mux.h"
#include "peripherals_osif_1.h"
#include "peripherals_csec_config_1.h"


#endif /* SDK_PROJECT_CONFIG_H_ */

